package cluster

const (
	PING_RETRIEVE   = "PING_RETRIEVE_TOPIC"
	PING_JOIN       = "PING_JOIN_TOPIC"
	PUSH            = "PUSH_TOPIC"
	PEER_CONNECTION = "PEER_CONNECTION_TOPIC"
	PEER_EXIT       = "PEER_EXIT_TOPIC"
	CLUSTER_JOIN    = "CLUSTER_JOIN_TOPIC"
)
